spring:
  datasource:
      url: jdbc:mysql://moaproject.cqkjko8dt72i.ap-northeast-2.rds.amazonaws.com:3306/corsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        #url: jdbc:mysql://127.0.0.1:3306/corsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: d3552468
        driver-class-name: com.mysql.cj.jdbc.Driver   
