spring:
  profiles:
    include:
    - aws
    - credentials
    - email

  datasource:
    url: jdbc:mysql://118.67.128.36:3306/corsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cors
    password: Dd3552468!
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 494377772043-o0tfbhk9ed4cn86u0r75m8256d57cc2u.apps.googleusercontent.com
            client-secret: yoOHGlFvC_4rxSyBXSFE2VB1
            
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

custom:
  oauth2:
    kakao:
      client-id: 61bd24470a52a968fb0af745df8dc26d
      client-secret: XNkkAWVhe9e82ycLbfS67yuNiVHHlRYy
    naver:
      client-id: ZzMs0mZ_U9ZVqzSpGXnr
      client-secret: zJh3U5N3Lt
