spring:
  profiles:
    include:
    - aws
    - credentials
    - email
    - oauth

  datasource:
    url: jdbc:mysql://115.85.183.222:3306/corsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://127.0.0.1:3306/corsdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cors
    password: Dd3552468!
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
            
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

